### ISSUE TITLE
crm-subject.btest: does not match (?^m:^Subject: .*#\])

### ISSUE THREAD

**Issue by robnagler** [biviosoftware/perl-Bivio#15]
`(?^m:^Subject: .*#\])` is missing `$num`, which must be empty.  The code for `$num`:

```perl
my($direct, $reflected) = map($_I->new($_), verify_local_mail($tech, undef, 2));
my($num) = $reflected->get_subject =~ qr{ #(\d+)\]};
```

This is the call that is failing:

```perl
    verify_local_mail($tech, qr{^Subject: .*#$num\]}m);
```

The last two log files are messages:

```txt
http-00028.eml:Subject: [Btest crm 2wzma9ja #3] subj-vvbyku0g
http-00029.eml:Subject: subj-xjmik5sb
```

Why isn't the verify_local_mail showing up in the log?

**Comment by robnagler** [comment]
passed today.

**Comment by moellep** [comment]
Seems to be running OK this morning with no changes.

**Comment by robnagler** [comment]
This seems to be a Sunday thing. I'm not going to reopen, just documenting
