### ISSUE TITLE
`Util/t/Host.t` may fail in dev

### ISSUE THREAD

**Issue by schellj** [biviosoftware/perl-Bivio#52]
```
[pet;@v perl-Bivio]$ bu Util/t/Host.t 
              Host.t: FAILED
Output:
  1..3
  ok 1
  not ok 2 Bivio::Util::Host=ARRAY(0x2bf58d0)#1->exec_if#1(case#2[[no-such-host,FAILED]]): Bivio::DieCode::DIE != [Not this host
  ]
  ok 3
  FAILED 1 (33.3%) and passed 2 (66.7%)
```
The logic (https://github.com/biviosoftware/perl-Bivio/blob/master/Util/Host.pm#L84) seems to be expecting `gethostbyname('ho-such-host')` to return an empty list of addresses (thus resulting in a `Bivio::Die->die("$host: gethostbyname error: $!")`, but an address may be returned:
```
[pet;@v perl-Bivio]$ perl -e '
>     my($name, $aliases, $addrtype, $length, @addrs) = gethostbyname("no-such-host");
>     for my $a (@addrs) {
>         my($a, $b, $c, $d) = unpack("W4", $a);
>         print "$a.$b.$c.$d\n";
>     }
> '
23.217.138.110
```
I'm assuming this has to due with the networking setup in the dev environment, but I'm not sure how to resolve it at this point.

**Comment by robnagler** [comment]
Your ISP is hacking DNS to get add revenue or something. I don't know what to do about that except specify the DNS servers on your VM, e.g. to be 8.8.8.8 8.8.4.4

**Comment by schellj** [comment]
Thanks. I think they do that to redirect from domains that aren't found to their "not found" landing page (with ads). 

Setting the DNS servers seems to have solved the issue. Should that be part of the standard setup? I think it's fairly common for ISPs to configure customers to use their DNS by default.

**Comment by robnagler** [comment]
We haven't had this problem, but it seems AT&T does this. I don't like overriding ISP's DNS without a good reason, because that can lead to other problems (like DNS being blocked).

**Comment by schellj** [comment]
I see. I'll go ahead and close this issue.
